import { formatAssetSize, getAssetTypeLabel } from '@/app/lib/contentful/mapping';
import type { EventEntry } from '@/app/lib/contentful/types';

export default function EventDocuments({ event }: { event: EventEntry }) {
  const documents = event.documents?.filter((document) => document.url) ?? [];
  if (!documents.length) return null;

  return <section className="scroll-mt-28 border-t border-rule pt-8" id="documents"><p className="mb-3 text-[0.72rem] font-bold uppercase tracking-[0.14em] text-brass">Player resources</p><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><h2 className="text-[clamp(2.3rem,5vw,4rem)] leading-none">Documents &amp; media</h2><p className="m-0 max-w-96 text-muted">Rules, guidance, and materials for this event.</p></div><div className="mt-8 grid gap-3">{documents.map((document) => { const file = document.fields?.file; const type = getAssetTypeLabel(file?.contentType); const size = formatAssetSize(file?.details?.size); return <a className="group grid min-h-11 gap-4 border border-rule bg-paper-raised p-4 text-ink no-underline transition-[transform,border-color,box-shadow] duration-200 ease-editorial hover:-translate-y-0.5 hover:border-brass hover:shadow-editorial sm:grid-cols-[4.5rem_minmax(0,1fr)_auto] sm:items-center sm:p-5" download href={document.url} key={document.sys?.id} rel="noreferrer" target="_blank"><span aria-hidden="true" className="grid aspect-square place-items-center bg-ink text-[0.68rem] font-bold tracking-[0.1em] text-brass">{type}</span><span className="min-w-0"><strong className="block text-xl leading-tight">{document.title ?? 'Event document'}</strong>{document.description ? <span className="mt-1 block text-sm leading-6 text-muted">{document.description}</span> : null}{size ? <span className="mt-2 block text-[0.7rem] font-bold uppercase tracking-[0.12em] text-muted">{size}</span> : null}</span><span className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-oxblood">Download <svg aria-hidden="true" className="size-4 transition-transform duration-200 group-hover:translate-y-0.5" fill="none" viewBox="0 0 24 24"><path d="M12 4v11m0 0 4-4m-4 4-4-4M5 20h14" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" /></svg></span></a>; })}</div></section>;
}
